#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './src/sort_into_names'
require_relative './src/export'
require_relative './src/report'

def args_valid?(args)
  args.length == 1
end

def print_usage
  puts 'Usage: name-sorter <filename>'
end

def print_file_error(file_name)
  puts "ERROR: File not found - #{file_name}"
end

def abort_application
  print_usage
  exit(-1)
end

abort_application unless args_valid?(ARGV)

input_file = ARGV.first

if File.exist?(input_file)
  lines = File.readlines(input_file)
  names = sort_into_names(lines)
  report(names)
  export(names)
else
  print_file_error(input_file)
end
